# Generated by bootstrap - fill in values after bootstrap apply
bucket         = "YOUR_STATE_BUCKET_NAME"
key            = "stage/terraform.tfstate"
region         = "us-east-1"
dynamodb_table = "terraform-state-lock"
encrypt        = true
