#!/bin/bash
# Helper script to generate backend config files from bootstrap outputs
# Usage: ./scripts/generate_backend_configs.sh

set -e

echo "========================================"
echo "Generate Backend Configs from Bootstrap"
echo "========================================"
echo ""

# Check if bootstrap state exists
if [ ! -f bootstrap/terraform.tfstate ]; then
    echo "❌ Bootstrap not applied yet (no terraform.tfstate in bootstrap/)"
    echo "   Run: cd bootstrap && terraform apply"
    exit 1
fi

# Extract backend config from bootstrap outputs
if command -v jq &>/dev/null; then
    BUCKET_NAME=$(jq -r '.outputs.state_bucket_name.value // empty' bootstrap/terraform.tfstate)
    LOCK_TABLE=$(jq -r '.outputs.lock_table_name.value // empty' bootstrap/terraform.tfstate)
    AWS_REGION=$(jq -r '.outputs.aws_region.value // empty' bootstrap/terraform.tfstate)
else
    echo "Using terraform output commands (jq not installed)..."
    BUCKET_NAME=$(cd bootstrap && terraform output -raw state_bucket_name 2>/dev/null)
    LOCK_TABLE=$(cd bootstrap && terraform output -raw lock_table_name 2>/dev/null)
    AWS_REGION=$(cd bootstrap && terraform output -raw aws_region 2>/dev/null)
fi

if [ -z "$BUCKET_NAME" ] || [ -z "$LOCK_TABLE" ]; then
    echo "❌ Could not extract backend config from bootstrap state"
    exit 1
fi

echo "Backend configuration:"
echo "  Bucket: $BUCKET_NAME"
echo "  Lock Table: $LOCK_TABLE"
echo "  Region: $AWS_REGION"
echo ""

# Generate backend configs for each environment
for ENV in dev stage prod; do
    BACKEND_FILE="environments/$ENV/backend-$ENV.hcl"
    
    echo "Writing $BACKEND_FILE..."
    
    cat > "$BACKEND_FILE" <<EOF
# Generated by scripts/generate_backend_configs.sh from bootstrap outputs
bucket         = "$BUCKET_NAME"
key            = "$ENV/terraform.tfstate"
region         = "$AWS_REGION"
dynamodb_table = "$LOCK_TABLE"
encrypt        = true
EOF

    echo "✅ $BACKEND_FILE created"
done

echo ""
echo "========================================"
echo "✅ Backend configs generated!"
echo "========================================"
echo ""
echo "Next steps:"
echo "  1. Review the backend-*.hcl files in environments/*/"
echo "  2. Initialize an environment: make init-dev"
echo "  3. Apply: make apply-dev"
